version: '3.8'
services:
   web :
    build: 
      context: .
      dockerfile: Dockerfile.dev
    # image: vallabh1421/production-workflow-dev
    ports:
      - "3000:3000"
    volumes :
      - /app/node_modules
      - .:/app
   server:
    build:
      context: .
      dockerfile: Dockerfile
    # image: vallabh1421/production-workflow-dev
    ports:
      - "8080:80"
   
      